Repository valentinaskn/2023_SLM_TicTacToe_Retro-Realm, pull requests merged in 2024-01, with the labels that each got.

#29 User Story 2 - view-game-state complete
  pom.xml
  src/main/java/Board.java
  src/main/java/TicTacToe.java
  src/test/java/BoardTest.java
Labels: user story

#36 User Story 3 - game-outcome-notification complete
  src/main/java/TicTacToe.java
  src/test/java/TicTacToeTest.java
Labels: user story

#39 Update and Document Generate JavaDoc Workflow
  .github/workflows/generateJavaDoc
  .github/workflows/generateJavaDoc.yml
Labels: bug, documentation

#47 General/final adjustments
  .idea/encodings.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  Projektangabe.md
  README.md
  RetroRealm_workflow-description.pdf
  pom.xml
  src/main/java/Board.java
  src/main/java/TicTacToe.java
  src/test/java/BoardTest.java
  src/test/java/PlayerTest.java
Labels: documentation, general

#48 final adjustments
  JavaDoc_RetroRealm_TicTacToe/Board.html
  JavaDoc_RetroRealm_TicTacToe/Player.html
  JavaDoc_RetroRealm_TicTacToe/TicTacToe.html
  JavaDoc_RetroRealm_TicTacToe/allclasses-index.html
  JavaDoc_RetroRealm_TicTacToe/allpackages-index.html
  JavaDoc_RetroRealm_TicTacToe/class-use/Board.html
  JavaDoc_RetroRealm_TicTacToe/class-use/Player.html
  JavaDoc_RetroRealm_TicTacToe/class-use/TicTacToe.html
  JavaDoc_RetroRealm_TicTacToe/element-list
  JavaDoc_RetroRealm_TicTacToe/help-doc.html
  JavaDoc_RetroRealm_TicTacToe/index-all.html
  JavaDoc_RetroRealm_TicTacToe/index.html
  JavaDoc_RetroRealm_TicTacToe/jquery-ui.overrides.css
  JavaDoc_RetroRealm_TicTacToe/legal/ADDITIONAL_LICENSE_INFO
  JavaDoc_RetroRealm_TicTacToe/legal/ASSEMBLY_EXCEPTION
  JavaDoc_RetroRealm_TicTacToe/legal/LICENSE
  JavaDoc_RetroRealm_TicTacToe/legal/jquery.md
  JavaDoc_RetroRealm_TicTacToe/legal/jqueryUI.md
  JavaDoc_RetroRealm_TicTacToe/member-search-index.js
  JavaDoc_RetroRealm_TicTacToe/module-search-index.js
  JavaDoc_RetroRealm_TicTacToe/overview-tree.html
  JavaDoc_RetroRealm_TicTacToe/package-search-index.js
  JavaDoc_RetroRealm_TicTacToe/package-summary.html
  JavaDoc_RetroRealm_TicTacToe/package-tree.html
  JavaDoc_RetroRealm_TicTacToe/package-use.html
  JavaDoc_RetroRealm_TicTacToe/resources/glass.png
  JavaDoc_RetroRealm_TicTacToe/resources/x.png
  JavaDoc_RetroRealm_TicTacToe/script-dir/jquery-3.6.1.min.js
  JavaDoc_RetroRealm_TicTacToe/script-dir/jquery-ui.min.css
  JavaDoc_RetroRealm_TicTacToe/script-dir/jquery-ui.min.js
  JavaDoc_RetroRealm_TicTacToe/script.js
  JavaDoc_RetroRealm_TicTacToe/search.js
  JavaDoc_RetroRealm_TicTacToe/stylesheet.css
  JavaDoc_RetroRealm_TicTacToe/tag-search-index.js
  JavaDoc_RetroRealm_TicTacToe/type-search-index.js
Labels: documentation
